---
title: "Double Lasso Assignment"
author: "Yotam Nir"
date: "27 6 2021"
output:
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 4
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Loading Packages

```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, hdm, stargazer, broom, knitr)
```

### Linear Model

```{r}
data("GrowthData")
y <- GrowthData$Outcome
d <- GrowthData$gdpsh465
x <- as.matrix(GrowthData %>% select(-c("Outcome", "gdpsh465", "intercept")))

varnames <- colnames(GrowthData)
xnames <-  varnames[-c(1, 2, 3)] # names of X variables
dandxnames <- varnames[-c(1, 2)] # names of D and X variables
fmla <- as.formula(paste("Outcome ~ ", paste(dandxnames, collapse = "+")))


ols <- lm(fmla, GrowthData)
partial_out <- rlassoEffect(x, y, d, method = "partialling out")
double_selection <- rlassoEffect(x, y, d, method = "double selection")


bind_rows(
  tidy(ols) %>% mutate(method = "full reg via ols") %>% filter(term == "gdpsh465") %>%
    select(method, estimate, std.error),
  tibble(
    method = "via post-lasso",
    estimate = summary(partial_out)[[1]][1,1],
    std.error = summary(partial_out)[[1]][1,2]
  ),
  tibble(
    method = "partial reg via double selection",
    estimate = summary(double_selection)[[1]][1,1],
    std.error = summary(double_selection)[[1]][1,2]
  )
) %>%
  kable(digits = 3, format = "html")
```


### IV Model

```{r}
data("AJR")
y <- AJR$GDP
d <- AJR$Exprop
z <- AJR$logMort
x <- model.matrix(~-1 + (Latitude + Latitude2 + Africa + Asia + Namer + Samer)^2, data = AJR)

lasso_IV <- rlassoIV(x, d, y, z, select.Z = FALSE, select.X = TRUE)
summary(lasso_IV)
confint(lasso_IV)


rY <- lm(GDP ~ (Latitude + Latitude2 + Africa + Asia + Namer + Samer)^2, data = AJR)$res
rD <- lm(Exprop ~ (Latitude + Latitude2 + Africa + Asia + Namer + Samer)^2, data = AJR)$res
rZ <- lm(logMort ~ (Latitude + Latitude2 + Africa + Asia + Namer + Samer)^2, data = AJR)$res

summary(tsls(rY ~ rD | rZ, intercept = FALSE))

rY <- rlasso(GDP ~ (Latitude + Latitude2 + Africa + Asia + Namer + Samer)^2, data = AJR)$res
rD <- rlasso(Exprop ~ (Latitude + Latitude2 + Africa + Asia + Namer + Samer)^2, data = AJR)$res
rZ <- rlasso(logMort ~ (Latitude + Latitude2 + Africa + Asia + Namer + Samer)^2, data = AJR)$res

summary(tsls(rY ~ rD | rZ, intercept = FALSE))
```


